### ISSUE TITLE
ImportError: No module named pymysql

### ISSUE THREAD

**Issue by yanchenko-igor** [hongqn/umysqldb#1]
setup.py need installed pymysql.

 $ python setup.py install
 Traceback (most recent call last):
 File "skiped/src/umysqldb/setup.py", line 3, in
 from umysqldb import **version**
 File "skiped/src/umysqldb/umysqldb/**init**.py", line 2, in
 import pymysql
 ImportError: No module named pymysql

**Comment by hongqn** [comment]
fixed in commit f4b40cc

thanks.
