### ISSUE TITLE
can you show some examples about using umysqldb with gevent?

### ISSUE THREAD

**Issue by sumory** [hongqn/umysqldb#5]
I am confused and working hard when i use gevent and mysql. Finally i find this module, can you show me some examples about how to use it with gevent and some points i should pay more attention to?

**Comment by hongqn** [comment]
``` python
>>> import gevent
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
>>> import umysqldb
>>> import time
>>> def f():
...   conn = umysqldb.connect(host='localhost')
...   curs = conn.cursor()
...   curs.execute("select sleep(1)")
...   print(time.time())
...
>>> gevent.joinall([gevent.spawn(f) for i in range(5)])
1384411726.76
1384411726.77
1384411726.77
1384411726.77
1384411726.77
```

**Comment by sumory** [comment]
```
import gevent
import gevent.monkey
gevent.monkey.patch_all()
import umysqldb
import time

conn = umysqldb.connect(host='localhost',user='root', passwd='root')

def f():
    curs = conn.cursor()
    curs.execute("select sleep(1)")
    print(time.time())

gevent.joinall([gevent.spawn(f) for i in range(5)])
```

会出现以下错误：

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\python\test_umysqldb.py", line 11, in f
    curs.execute("select sleep(1)")
  File "C:\Python27\lib\site-packages\umysqldb\cursors.py", line 20, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\umysqldb\connections.py", line 43, in defaulterrorhandler
    raise errorclass, errorvalue
InternalError: (0, 'Concurrent access in query method')
<Greenlet at 0x2e892a8L: f> failed with InternalError

```

是不是每次使用umysqldb时都要先建立连接，这样频繁建立的代价会不会很大？
在gevent里使用umysqldb是否需要另行建立连接池呢？

**Comment by hongqn** [comment]
MySQL 的连接是不能多线程同时使用的。希望复用连接的话可以使用连接池，比如用 https://github.com/CMGS/pool
